# Generated by Django 2.2.13 on 2021-02-14 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoJob',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('job_function', models.CharField(max_length=128)),
                ('job_parameters', models.TextField(blank=True)),
                ('gmt_update', models.DateTimeField(auto_now=True)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('gmt_update',),
            },
        ),
        migrations.CreateModel(
            name='JobExecHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_instance_id', models.CharField(max_length=64, unique=True)),
                ('job_name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('status', models.CharField(choices=[['Running', 'Running'], ['Success', 'Success'], ['Error!', 'Error!']], max_length=50)),
                ('start_tm', models.DateTimeField(auto_now_add=True)),
                ('end_tm', models.DateTimeField(auto_now=True)),
                ('trace_message', models.TextField(blank=True, verbose_name='追踪日志')),
                ('gmt_update', models.DateTimeField(auto_now=True)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background_job.DjangoJob')),
            ],
            options={
                'ordering': ('-start_tm',),
            },
        ),
    ]
