# Generated by Django 2.2.13 on 2021-02-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexechistory',
            name='result',
            field=models.TextField(blank=True, null=True, verbose_name='执行返回结果'),
        ),
    ]
