# Generated by Django 2.2.13 on 2021-02-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangojob',
            name='allow_parallel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='djangojob',
            name='cron',
            field=models.CharField(default='* * * * *', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='djangojob',
            name='max_instances',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='djangojob',
            name='misfire_grace_time',
            field=models.IntegerField(default=0),
        ),
    ]
