# Generated by Django 2.2.13 on 2021-02-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_job', '0002_auto_20210224_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexechistory',
            name='trace_message',
            field=models.TextField(blank=True, null=True, verbose_name='追踪日志'),
        ),
    ]
