# Generated by Django 3.1.6 on 2021-02-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_job', '0003_auto_20210224_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='op_host',
            field=models.CharField(max_length=128, verbose_name='操作来源'),
        ),
        migrations.AlterField(
            model_name='jobexechistory',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
