# Generated by Django 2.2.13 on 2021-02-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_job', '0003_auto_20210214_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djangojob',
            old_name='cron',
            new_name='trigger_expression',
        ),
        migrations.AddField(
            model_name='djangojob',
            name='log_err_interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='djangojob',
            name='log_succ_interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='djangojob',
            name='trigger_type',
            field=models.CharField(choices=[['cron', 'cron'], ['interval', 'interval'], ['once', 'once'], ['delayedjob', 'delayedjob']], default='* * */1 * *', max_length=128),
            preserve_default=False,
        ),
    ]
