# Generated by Django 2.2.13 on 2021-02-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background_job', '0004_auto_20210215_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djangojob',
            old_name='allow_parallel',
            new_name='coalesce',
        ),
    ]
