# Generated by Django 2.2.13 on 2021-02-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_job', '0005_auto_20210215_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayedJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('job_function', models.CharField(max_length=128)),
                ('job_parameters', models.TextField(blank=True)),
                ('retry', models.IntegerField(default=0)),
                ('retry_cnt', models.IntegerField(default=0)),
                ('gmt_update', models.DateTimeField(auto_now=True)),
                ('gmt_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('gmt_update',),
            },
        ),
    ]
