# Generated by Django 3.1.6 on 2021-02-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_job', '0006_delayedjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobexechistory',
            name='job_instance_id',
        ),
        migrations.AlterField(
            model_name='djangojob',
            name='trigger_type',
            field=models.CharField(choices=[['cron', 'cron'], ['interval', 'interval'], ['once', 'once']], max_length=128),
        ),
    ]
