# Generated by Django 3.1.6 on 2021-02-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_job', '0008_auto_20210219_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='delayedjob',
            name='version',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='djangojob',
            name='version',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobexechistory',
            name='version',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
