# Generated by Django 2.2.13 on 2021-02-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_job', '0009_auto_20210220_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexechistory',
            name='status',
            field=models.CharField(choices=[['New', 'New'], ['Running', 'Running'], ['Success', 'Success'], ['Error!', 'Error!'], ['Max instances reached!', 'Max instances reached!'], ['Missed!', 'Missed!']], max_length=50),
        ),
    ]
